use_frameworks!
platform :ios, '9.0'

target 'FoodSwift' do
  pod 'Koloda'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Firebase'
  pod 'SVProgressHUD'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Facebook', '~> 3.0'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

  post_install do |installer|
	  installer.pods_project.targets.each do |target|
	      target.build_configurations.each do |config|
	          config.build_settings['SWIFT_VERSION'] = '3.0'
	      end
	   end
	end

end
