use_frameworks!
platform :ios, '9.0'

target 'FoodSwift' do
  pod 'Koloda'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Facebook', '~> 3.0'  
	post_install do |installer|
	  installer.pods_project.targets.each do |target|
	      target.build_configurations.each do |config|
	          config.build_settings['SWIFT_VERSION'] = '3.0'
	      end
	   end
	end

end
